language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
before_script:
  - npm run test
script:
  - npx semantic-release
after_script:
  - bash <(curl -s https://codecov.io/bash)