const htmlAttributes: Map<string, Array<string>> = new Map<string, Array<string>>();

htmlAttributes.set('accept', ["form", "input"]);
htmlAttributes.set('accept-charset', ["form"]);
htmlAttributes.set('accesskey', ["*"]);
htmlAttributes.set('action', ["form"]);
htmlAttributes.set('align', ["applet", "caption", "col", "colgroup", "hr", "iframe", "img", "table", "tbody", "td", "tfoot", "th", "thead", "tr"]);
htmlAttributes.set('allow', ["iframe"]);
htmlAttributes.set('alt', ["applet", "area", "img", "input"]);
htmlAttributes.set('async', ["script"]);
htmlAttributes.set('autocapitalize', ["*"]);
htmlAttributes.set('autocomplete', ["form", "input", "select", "textarea"]);
htmlAttributes.set('autofocus', ["button", "input", "keygen", "select", "textarea"]);
htmlAttributes.set('autoplay', ["audio", "video"]);
htmlAttributes.set('background', ["body", "table", "td", "th"]);
htmlAttributes.set('bgcolor', ["body", "col", "colgroup", "marquee", "table", "tbody", "tfoot", "td", "th", "tr"]);
htmlAttributes.set('border', ["img", "object", "table"]);
htmlAttributes.set('buffered', ["audio", "video"]);
htmlAttributes.set('capture', ["input"]);
htmlAttributes.set('challenge', ["keygen"]);
htmlAttributes.set('charset', ["meta", "script"]);
htmlAttributes.set('checked', ["command", "input"]);
htmlAttributes.set('cite', ["blockquote", "del", "ins", "q"]);
htmlAttributes.set('class', ["*"]);
htmlAttributes.set('code', ["applet"]);
htmlAttributes.set('codebase', ["applet"]);
htmlAttributes.set('color', ["basefont", "font", "hr"]);
htmlAttributes.set('cols', ["textarea"]);
htmlAttributes.set('colspan', ["td", "th"]);
htmlAttributes.set('content', ["meta"]);
htmlAttributes.set('contenteditable', ["*"]);
htmlAttributes.set('contextmenu', ["*"]);
htmlAttributes.set('controls', ["audio", "video"]);
htmlAttributes.set('coords', ["area"]);
htmlAttributes.set('crossorigin', ["audio", "img", "link", "script", "video"]);
htmlAttributes.set('csp', ["iframe"]);
htmlAttributes.set('data', ["object"]);
htmlAttributes.set('data-*', ["*"]);
htmlAttributes.set('datetime', ["del", "ins", "time"]);
htmlAttributes.set('decoding', ["img"]);
htmlAttributes.set('default', ["track"]);
htmlAttributes.set('defer', ["script"]);
htmlAttributes.set('dir', ["*"]);
htmlAttributes.set('dirname', ["input", "textarea"]);
htmlAttributes.set('disabled', ["button", "command", "fieldset", "input", "keygen", "optgroup", "option", "select", "textarea"]);
htmlAttributes.set('download', ["a", "area"]);
htmlAttributes.set('draggable', ["*"]);
htmlAttributes.set('dropzone', ["*"]);
htmlAttributes.set('enctype', ["form"]);
htmlAttributes.set('enterkeyhint', ["textarea", "contenteditable"]);
htmlAttributes.set('for', ["label", "output"]);
htmlAttributes.set('form', ["button", "fieldset", "input", "keygen", "label", "meter", "object", "output", "progress", "select", "textarea"]);
htmlAttributes.set('formaction', ["input", "button"]);
htmlAttributes.set('formenctype', ["button", "input"]);
htmlAttributes.set('formmethod', ["button", "input"]);
htmlAttributes.set('formnovalidate', ["button", "input"]);
htmlAttributes.set('formtarget', ["button", "input"]);
htmlAttributes.set('headers', ["td", "th"]);
htmlAttributes.set('height', ["canvas", "embed", "iframe", "img", "input", "object", "video"]);
htmlAttributes.set('hidden', ["*"]);
htmlAttributes.set('high', ["meter"]);
htmlAttributes.set('href', ["a", "area", "base", "link"]);
htmlAttributes.set('hreflang', ["a", "area", "link"]);
htmlAttributes.set('http-equiv', ["meta"]);
htmlAttributes.set('icon', ["command"]);
htmlAttributes.set('id', ["*"]);
htmlAttributes.set('importance', ["iframe", "img", "link", "script"]);
htmlAttributes.set('integrity', ["link", "script"]);
htmlAttributes.set('intrinsicsize', ["img"]);
htmlAttributes.set('inputmode', ["textarea", "contenteditable"]);
htmlAttributes.set('ismap', ["img"]);
htmlAttributes.set('itemprop', ["*"]);
htmlAttributes.set('keytype', ["keygen"]);
htmlAttributes.set('kind', ["track"]);
htmlAttributes.set('label', ["optgroup", "option", "track"]);
htmlAttributes.set('lang', ["*"]);
htmlAttributes.set('language', ["script"]);
htmlAttributes.set('loading', ["img", "iframe"]);
htmlAttributes.set('list', ["input"]);
htmlAttributes.set('loop', ["audio", "bgsound", "marquee", "video"]);
htmlAttributes.set('low', ["meter"]);
htmlAttributes.set('manifest', ["html"]);
htmlAttributes.set('max', ["input", "meter", "progress"]);
htmlAttributes.set('maxlength', ["input", "textarea"]);
htmlAttributes.set('minlength', ["input", "textarea"]);
htmlAttributes.set('media', ["a", "area", "link", "source", "style"]);
htmlAttributes.set('method', ["form"]);
htmlAttributes.set('min', ["input", "meter"]);
htmlAttributes.set('multiple', ["input", "select"]);
htmlAttributes.set('muted', ["audio", "video"]);
htmlAttributes.set('name', ["button", "form", "fieldset", "iframe", "input", "keygen", "object", "output", "select", "textarea", "map", "meta", "param"]);
htmlAttributes.set('novalidate', ["form"]);
htmlAttributes.set('open', ["details"]);
htmlAttributes.set('optimum', ["meter"]);
htmlAttributes.set('pattern', ["input"]);
htmlAttributes.set('ping', ["a", "area"]);
htmlAttributes.set('placeholder', ["input", "textarea"]);
htmlAttributes.set('poster', ["video"]);
htmlAttributes.set('preload', ["audio", "video"]);
htmlAttributes.set('radiogroup', ["command"]);
htmlAttributes.set('readonly', ["input", "textarea"]);
htmlAttributes.set('referrerpolicy', ["a", "area", "iframe", "img", "link", "script"]);
htmlAttributes.set('rel', ["a", "area", "link"]);
htmlAttributes.set('required', ["input", "select", "textarea"]);
htmlAttributes.set('reversed', ["ol"]);
htmlAttributes.set('rows', ["textarea"]);
htmlAttributes.set('rowspan', ["td", "th"]);
htmlAttributes.set('sandbox', ["iframe"]);
htmlAttributes.set('scope', ["th"]);
htmlAttributes.set('scoped', ["style"]);
htmlAttributes.set('selected', ["option"]);
htmlAttributes.set('shape', ["a", "area"]);
htmlAttributes.set('size', ["input", "select"]);
htmlAttributes.set('sizes', ["link", "img", "source"]);
htmlAttributes.set('slot', ["*"]);
htmlAttributes.set('span', ["col", "colgroup"]);
htmlAttributes.set('spellcheck', ["*"]);
htmlAttributes.set('src', ["audio", "embed", "iframe", "img", "input", "script", "source", "track", "video"]);
htmlAttributes.set('srcdoc', ["iframe"]);
htmlAttributes.set('srclang', ["track"]);
htmlAttributes.set('srcset', ["img", "source"]);
htmlAttributes.set('start', ["ol"]);
htmlAttributes.set('step', ["input"]);
htmlAttributes.set('style', ["*"]);
htmlAttributes.set('summary', ["table"]);
htmlAttributes.set('tabindex', ["*"]);
htmlAttributes.set('target', ["a", "area", "base", "form"]);
htmlAttributes.set('title', ["*"]);
htmlAttributes.set('translate', ["*"]);
htmlAttributes.set('type', ["button", "input", "command", "embed", "object", "script", "source", "style", "menu"]);
htmlAttributes.set('usemap', ["img", "input", "object"]);
htmlAttributes.set('value', ["button", "data", "input", "li", "meter", "option", "progress", "param"]);
htmlAttributes.set('width', ["canvas", "embed", "iframe", "img", "input", "object", "video"]);
htmlAttributes.set('wrap', ["textarea"]);

export default function isValidAttribute(attributeName: string, tag: string) {
    return htmlAttributes.has(attributeName) && htmlAttributes.get(attributeName).indexOf(tag.toLowerCase()) >= 0
};
